# Nautilus Simulation Bridge Parameters

# Parameters under /** are shared by all nodes that load this file
/**:
  ros__parameters:
    model_name: "glider_nautilus"

nautilus_bcu_bridge:
  ros__parameters: {}

nautilus_acu_bridge:
  ros__parameters: {}
  
# These nodes will now automatically inherit 'model_name' from the /** block
nautilus_external_sensor_bridge:
  ros__parameters: {}

nautilus_imu_bridge:
  ros__parameters: {}
