name: Sync Fork
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v2.0
        with:
          owner: IOES-Lab  # Owner of the upstream repo
          head: ros2        # Branch from upstream
          base: dev        # Branch in your fork to update